#!/usr/bin/env bash
# Seeds (or reuses) a SECOND fixed test account against the LOCAL Supabase
# stack -- the "target" a search/block flow looks up and acts on, distinct
# from the fixed E2E account seed-test-user.sh creates. Idempotent: safe to
# run before every E2E run. Never touches anything but
# http://127.0.0.1:54321 -- see seed-test-user.sh for why the service role
# key below is safe to commit.
#
# Prints the target's unique_user_id (e.g. "FC-100007") as the ONLY line on
# stdout, so a caller can capture it directly:
#   TARGET_CODE="$(./seed-target-user.sh)"
# unique_user_id is sequence-generated by the DB trigger
# generate_unique_user_id() and cannot be set manually (it raises if
# new.unique_user_id is not null), so it isn't known ahead of time -- this
# script looks it up after creation (or reuse) instead of assuming one.
#
# Also clears any user_blocks row between the fixed E2E account and this
# target on every run (both directions), so a flow that blocks the target
# (search-and-block-user.yaml) starts from the same clean relationship
# state every time -- without this, a second run would find "Blocca"
# already replaced by "Sblocca" and fail at that step.
set -euo pipefail

SUPABASE_URL="http://127.0.0.1:54321"
SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"

E2E_TARGET_PHONE="+390000000999"
E2E_TARGET_PASSWORD="MaestroTarget123!"

EXISTING_ID=$(docker exec -i supabase_db_backend-foundation psql -U postgres -d postgres -tA -c \
  "select id from auth.users where phone = '${E2E_TARGET_PHONE#+}';" 2>/dev/null | tr -d '[:space:]')

if [ -z "$EXISTING_ID" ]; then
  RESPONSE=$(curl -s -X POST "$SUPABASE_URL/auth/v1/admin/users" \
    -H "apikey: $SERVICE_ROLE_KEY" \
    -H "Authorization: Bearer $SERVICE_ROLE_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"phone\":\"$E2E_TARGET_PHONE\",\"password\":\"$E2E_TARGET_PASSWORD\",\"phone_confirm\":true}")

  USER_ID=$(echo "$RESPONSE" | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>console.log(JSON.parse(d).id))")

  if [ -z "$USER_ID" ] || [ "$USER_ID" = "undefined" ]; then
    echo "Failed to create target auth user. Response was: $RESPONSE" >&2
    exit 1
  fi

  docker exec -i supabase_db_backend-foundation psql -U postgres -d postgres -c "
  insert into public.users (id, phone, first_name, last_name, birth_date, height_cm, preferred_foot, player_role)
  values ('$USER_ID', '$E2E_TARGET_PHONE', 'Bersaglio', 'E2E', '1998-06-15', 175, 'left', 'player');
  " >/dev/null
else
  USER_ID="$EXISTING_ID"
fi

TARGET_CODE=$(docker exec -i supabase_db_backend-foundation psql -U postgres -d postgres -tA -c \
  "select unique_user_id from public.users where id = '$USER_ID';" 2>/dev/null | tr -d '[:space:]')

if [ -z "$TARGET_CODE" ]; then
  echo "Target user exists in auth.users but not public.users -- inconsistent seed state." >&2
  exit 1
fi

E2E_PHONE="+390000000900"
E2E_ID=$(docker exec -i supabase_db_backend-foundation psql -U postgres -d postgres -tA -c \
  "select id from auth.users where phone = '${E2E_PHONE#+}';" 2>/dev/null | tr -d '[:space:]')

if [ -n "$E2E_ID" ]; then
  docker exec -i supabase_db_backend-foundation psql -U postgres -d postgres -c "
  delete from public.user_blocks
  where (blocker_id = '$E2E_ID' and blocked_id = '$USER_ID')
     or (blocker_id = '$USER_ID' and blocked_id = '$E2E_ID');
  " >/dev/null
fi

echo "$TARGET_CODE"
